server :
  port : 8081
  servlet :
    context-path : /pxxbms

spring :
  datasource :
    type : com.alibaba.druid.pool.DruidDataSource
    url : jdbc:mysql://120.25.170.3:3306/pxx?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name : com.mysql.cj.jdbc.Driver
    username : pxx_admin
    password : 123456
  
  thymeleaf :
    cache : false
  messages :
    basename : i18n.login
    encoding : UTF-8
  mvc :
    format :
      date : yyyy-MM-dd
    pathmatch :
      matching-strategy : ant_path_matcher


swagger2 :
  enable : fale
